### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by willtco** [fbergama/pigfx#13]

**Comment by willtco** [comment]
Apologies for posting in error.

**Comment by fordp2002** [comment]
When set to 8 bits you will only ever see 9 bits on the scope. The stop bits is the same level as the idle bit so you can only ever see the start of the stop bit. If you send consecutive bytes you can sort of see the end of the start bit as it is the same as the start of the start bit for the next character.

**Comment by willtco** [comment]
Yes,  I realised that (eventually), and tried to delete the post but, it does not seem possible - thanks for the reply.

**Comment by chregu82** [comment]
This doesn't seem to need attention anymore.
