### ISSUE TITLE
Pi Zero version 1.3

### ISSUE THREAD

**Issue by TheCodeman** [fbergama/pigfx#2]
pigfx does not seems to start on the new pi zero v1.3 
only some random junk on the screen .
ken

**Comment by fbergama** [comment]
I've tested it successfully on a plain old Pi first model and Pi Zero. I thought that the 1.3 version is no different from those except for the camera connector. 

It may be due to different addresses of some hardware peripherals. Can you do some tests?

**Comment by foxweb** [comment]
I have 4 RPi boards (1, 2, 3, Zero) and I will try all of them (but I don't promise).

**Comment by fbergama** [comment]
I can already tell you that it won't work on raspi 2 and 3 due to different peripheral addresses.
This can be fixed but I don't have time right now :(

**Comment by foxweb** [comment]
So, I have Pi Zero v1.3 and SD-card with PiGFX from Spencer. This kit has been started properly at once and not modified firmware or changed Pi board.

![img_3593](https://cloud.githubusercontent.com/assets/51654/18520670/e18f67ec-7ab9-11e6-98d7-47f56815653e.jpg)

**Comment by fbergama** [comment]
So, you confirm that it works on the Pi 1.3 with the unmodified firmware you received by spencer. Right?

Can you please test the following:

- update your repo to the latest commit of pigfx/master 
- copy bin/kernel.bin to your raspi sd card. Leave all the other files untouched
- turn on the whole system and check if everything works

Thank you for your effort :)

**Comment by foxweb** [comment]
> So, you confirm that it works on the Pi 1.3 with the unmodified firmware you received by spencer. Right?

Yep!

Please wait a few hours.

**Comment by fbergama** [comment]
Ok so it's definitely not an hardware problem. If my kernel.img works it must be related to TheCodeman toolchain/system

**Comment by TheCodeman** [comment]
Just reinstalled and rebuilt it all and seems ok now ? 
Not sure what it was . 
ken

**Comment by fbergama** [comment]
Good news!
So.. I'll close the issue.

@foxweb: the test is not needed anymore, but thank you very much for your effort 👍

**Comment by foxweb** [comment]
@fbergama @TheCodeman I have built the latest `kernel.img` and it works so good as unmodified firmware from Spencer.

![img_3731](https://cloud.githubusercontent.com/assets/51654/18527575/64fc8e18-7ad6-11e6-84b8-233db6051d7a.JPG)

**Comment by fbergama** [comment]
Great! Thank you
