### ISSUE TITLE
Problem building

### ISSUE THREAD

**Issue by clausmunk** [fbergama/pigfx#25]
I'm trying to build the latest version but get the following error:

cc1: error: '-mfloat-abi=hard': selected processor lacks an FPU

I'm using "arm-none-eabi-gcc (GNU Tools for Arm Embedded Processors 9-2019-q4-major) 9.2.1 20191025 (release) [ARM/arm-9-branch revision 277599]" under MacOS.

Any hints?

**Comment by chregu82** [comment]
Are you trying to build the master or the raspi2 branch?

**Comment by clausmunk** [comment]
I have tried both. Same result. I also get the error when trying to build the uspi subcomponent.

**Comment by chregu82** [comment]
Raspi2 branch is work in progress. It won't boot. I checked my gcc version, I'm on 7.4.0, which seems to work. You probably need to change some compiler options for newer gcc, but I'm not sure.

**Comment by clausmunk** [comment]
Ok, I’ll try to dig up an old version of the tool chain.

Thanks

**Comment by chregu82** [comment]
PiGFX should now be buildable with the latest toolchain.
