### ISSUE TITLE
Cannot print ESC literal. Missing up-left box character.

### ISSUE THREAD

**Issue by Herobrine2Nether** [fbergama/pigfx#3]
I can print the up-right character with ^Z, and the X character with ^\ yet ^[ waits indefinitely for an escape sequence. Can a time-out or additional sequence be implemented to allow the up-left box character to be printed?
![characters](https://cloud.githubusercontent.com/assets/12076803/24429431/3faebd60-13cf-11e7-81d0-88e23d90429e.png)
![cbios_main_msx1_256w](https://cloud.githubusercontent.com/assets/12076803/24429433/40ff8244-13cf-11e7-865b-63cf287ac8e4.png)

**Comment by fbergama** [comment]
You are right, I assume that after the escape character an escape sequence occurs. Hence, there is no way now to output the escape char itself. 
I haven't got much time now, but it should be an easy change to fix

**Comment by fbergama** [comment]
Ok if you update to the latest commit on master you should be able to output the ESC character by typing the ESC twice. Hope this closes the issue.
