### ISSUE TITLE
Pi 3 Model B

### ISSUE THREAD

**Issue by lindoran** [fbergama/pigfx#32]
on 1.7.0 the terminal will not load past showing the baud rate. on the Pi 3 Model B

**Comment by chregu82** [comment]
I just tried this again and found no problems. Did you send at least 8 characters to the terminal? Baudrate is right? Is your ACT LED still flashing?

**Comment by lindoran** [comment]
yes it is working on the pi zero but not on the Pi 3 Model B v1.2

**Comment by lindoran** [comment]
i will try to make a video later today

**Comment by chregu82** [comment]
My Pi3 Model B V1.2 works fine on V1.7.0. Is your LED still flashing? Is it working on V1.6.x?

**Comment by lindoran** [comment]
I will try and get back to you :) probably a couple of hours

**Comment by lindoran** [comment]
I went back and tried with 1.6.2 and the terminal is not working there so it must be a problem with the UART pins on my pi 3.  My apologies the good news is my pi zero does work so ill do the remainder of the testing with that thanks for checking on your end ill try to be more thorough in the future
