### ISSUE TITLE
# inline following a <esc> when its not required (typo) will cause a crash where previously it was ignored.

### ISSUE THREAD

**Issue by lindoran** [fbergama/pigfx#33]
Don't know if this is a Huge issue but I had a bug in one of my test programs where i misrepresented the change background color code as '#48;5;' instead of '48;5' .... it was a typo.  The terminal was not expecting this input and it caused a full crash and the ACT light would lock up on the pi. I don't know if this is a issue with the string parser that handles the escape codes? It was fully working in the previous version not causing any issue (simply ignoring and changing the background color anyway). but since the adding of the new sprite commands this is now causing a issue; but only with this typo that I can tell.   it doesn't seem to cause an issue anywhere in the string, you can place a # mid string and as long as it does not follow an esc character you are good the terminal ignores it. IDK why i have this kind of luck... fortunately this time i found my mistake before issuing a ticket. I was using a Pi Zero (non w) for this test.

**Comment by chregu82** [comment]
Thanks for posting this issue.
This typo triggered the new move sprite command, but with invalid parameters which caused the Pi to crash. This is fixed in V1.7.1.

**Comment by lindoran** [comment]
thanks :)
