### ISSUE TITLE
How do you debug it?

### ISSUE THREAD

**Issue by wrljet** [fbergama/pigfx#42]
How do you debug the code?

**Comment by chregu82** [comment]
I always write perfectly working code, so there's no need for debugging.

----

Actually, no. I usually do this:
- Write code, if it compiles, I test it.
- If it fails, I think about it and review what I did.
- If it still fails, I write debug code which outputs some states and variables to the screen or to the serial port, if there's no framebuffer yet.
- I also recently added an exception handler which outputs the program counter and several registers at a crash. That's quite helpful sometimes.

**Comment by wrljet** [comment]
I asked because I saw the JTAG directory with GDB stuff in it.

**Comment by chregu82** [comment]
I never used JTAG, but someone did this in the early development.

**Comment by fbergama** [comment]
Yea I did it with a cheap JTAG dongle at the beginning. Not particularly easy though. At this point it is probably easier to just print something at screen

**Comment by wrljet** [comment]
Thanks, BTW.../Bill
