### ISSUE TITLE
README doesn't list compatible Raspberry Pi models

### ISSUE THREAD

**Issue by MustBeArt** [fbergama/pigfx#5]
There's nothing in the README (or any other document I found) to explain which versions of Raspberry Pi are compatible with PiGFX.

There's a mention of "all Raspberry Pi models" in the warning about serial port voltage, which seems to suggest that it runs on all of them. But I found an issue comment where you said it would not work on model 2 or 3, and I saw in an RC2014 document that it doesn't work on the Pi Zero W. Unfortunately I didn't find that issue comment until after I'd struggled for a while trying to get PiGFX to work on a Pi 3.

**Comment by huskeyw** [comment]
I cant get it to work on any pi, just a rainbow screen at best

**Comment by chregu82** [comment]
It is only working on a Raspberry Pi Generation 1 model at the moment.

**Comment by chregu82** [comment]
It's written in the README now that at the moment only generation 1 is supported.

**Comment by MustBeArt** [comment]
It works on Raspberry Pi Zero as well. (But not Pi Zero W). That’s what the RC2014 serial terminal board based on PiGFX uses.
