### ISSUE TITLE
Compiling Error

### ISSUE THREAD

**Issue by ProgrammingCube** [fbergama/pigfx#57]
I think I have the arm cross compiler toolchain set up correctly, but I always seem to be "that guy" when setting up dev environments...

I got the uspi cloned into the right directory and there's no error from gcc, but I am getting these errors:

`/bin/sh: 1: [: 4: unexpected error`
![Screenshot from 2021-04-26 10-57-28](https://user-images.githubusercontent.com/17225550/116104417-69707580-a67e-11eb-8b06-20603bb1170d.png)

**Comment by chregu82** [comment]
It looks to me as if this part of the makefile doesn't work:
kernel: pigfx.img
	@if [ $(RPI) == 1 ]; then \
		cp pigfx.img bin/kernel.img; \
	elif [ $(RPI) == 2 ]; then \
		cp pigfx.img bin/kernel7.img; \
	elif [ $(RPI) == 3 ]; then \
		cp pigfx.img bin/kernel8-32.img; \
	else \
		cp pigfx.img bin/recovery7l.img; \
	fi;

But I have no idea why...

**Comment by ProgrammingCube** [comment]
Funny enough, I did the same steps but on my home pc with windows 10, and it worked perfectly. So that's strange.

**Comment by chregu82** [comment]
Compiling on Windows is completely different than on linux. The makefile isn't used at all on Windows. There's a batch file that handles compiling.

**Comment by ProgrammingCube** [comment]
Interesting, my friend was able to compile on linux no problem. I tried downloading and compiling on my home pc, but the same error popped up. Is it possible its a toolchain issue?

EDIT
I had my friend send me a copy of his Makefile, and wouldn't you know it, it worked. I am at a loss for words

**Comment by chregu82** [comment]
I'm going to close this if you don't mind.
