### ISSUE TITLE
How to load custom fonts?

### ISSUE THREAD

**Issue by ProgrammingCube** [fbergama/pigfx#59]
I'm making a cp 437 font for the pigfx, but I am unsure of how to load it from the sd card. The terminal codes don't seem to have a command to do so, but they do have a way to load 1 of the 3 trs font sizes.

**Comment by chregu82** [comment]
Loading custom fonts at runtime is not implemented. At the moment the only possible way is to modify the source code with your own font.

**Comment by ProgrammingCube** [comment]
damn, got it! I'll try doing that
