### ISSUE TITLE
unable to correctly set baudrate.

### ISSUE THREAD

**Issue by willtco** [fbergama/pigfx#65]
I have followed the instructions to the letter,  yet when booting the pi it indicates that the uart is expecting data at 115200 rather than the 9600buad set in pigfx.txt.  I am using a pi-zero.  It appears that pigfx is being ignored,  I compiled the build as later I wish to modify the gfx.c file (but at the time of writing no changes have been made).

**Comment by chregu82** [comment]
Please read this issue: https://github.com/fbergama/pigfx/issues/56

Does it even read the filesystem on the SD card?

**Comment by willtco** [comment]
Thanks for the reply, The pi boots up fine, at the bottom of the screen there's a message indicating the uart is waiting for 115200 8 n 1  - when I press a key on the keyboard a string of garbage appears, it seems clear that although 9600baud is set in the .txt file it only wants to play the 115200 baud rate.  The issue you mention seems to be something quite different.

**Comment by chregu82** [comment]
Please post a picture of your boot screen. I'm quite sure that PiGFX is unable to read the SD card and therefore cannot read the config file and therefore uses the default baudrate of 115200.

**Comment by willtco** [comment]
/media/dadmin/NEW VOLUME/DCIM/100CASIO/CIMG5316.JPG

**Comment by willtco** [comment]
![CIMG5316](https://user-images.githubusercontent.com/42438222/131299198-bec9f9d7-a165-46e3-8fb0-934368920c1a.JPG)
This photo is of a compile of the downloaded uspi & piGFX zip files without any modification.  afterlooking through the source I found the default is located in 'config.c'  - when changing the default  .uartBaudrate to 38400 my z80 card was able to send data to the pi and it was correctly represented on screen. However  the usb keyboard was inoperative (except for the function keys which produced a few characters of garbage. My 2019 pigfix has many updates which I hope to transfer to the latest edition hence my need to compile from source - I thank you for your patience. 

> [<img alt="@willtco" width="40" height="40" src="https://avatars.githubusercontent.com/u/42438222?s=80&amp;v=4">](/willtco)

**Comment by chregu82** [comment]
It's like I thought. PiGFX is unable to read the SD card. You seem to have 4 partitions on your card. This doesn't work. Please delete all partitions, add a single new one, format it and put PiGFX on it. It should work afterwards.

**Comment by willtco** [comment]
![part](https://user-images.githubusercontent.com/42438222/131305717-efdbb039-5e08-4a7d-84b6-c4270d013471.png)
Yes I thought that but making a second card produced the same results, Using linux mint to examine the card shows only a single FAT partition,  as below, the card was formatted under windows, it is a 2GB card as that's the smallest one I have. It contains only the few files for piGFX.

**Comment by chregu82** [comment]
Could you use the windows tool for checking the partitions on the SD card? There seem to be more than your linux mint shows. If there's only one FAT formatted partition it should work fine.

**Comment by willtco** [comment]
![pi](https://user-images.githubusercontent.com/42438222/131308367-c71d06d7-b235-45c7-b5c3-b477b7bb862d.png)

WIndows shows only a single partition as well - very confusing.

**Comment by chregu82** [comment]
Does this SD card produce the boot screen you showed earlier?

**Comment by willtco** [comment]
I think (dare I say it) that the problem may be with your MBR reader,  for large partitions it shows  "MBR: found total of 0 partition(s)"  - and for a small partition it seems to be reading the wrong sector and mis-interpreting ascii messages as partition records. - if you can point me to the source code for this part I'll take a close look. - I knew 17 years in the disk industry might come in handy one day!

**Comment by willtco** [comment]
yes same one.

**Comment by willtco** [comment]
Can you upload the MBR of a working card?  - it should start with EB and end with 55 AA - I'll graft that onto a card, then format it - I think at some time the MBR - here is the MBR of the re-formatted 2gb card it clearly shows that Windows has replaced the true mbr  with the first sector of a partition.  If I can replace this with a good mbr from a 1GB card then reformat I believe that will cure the baudrate problem,  but whether it will also cure the USB KBD I'm not sure 
![Untitled](https://user-images.githubusercontent.com/42438222/131327097-9a52eb00-4f1a-4e74-88a2-4b400a833b83.png)

**Comment by willtco** [comment]
Update - after grafting a 500mb Fat 16 MBR onto the SD card, & re-formatting - the first part of the problem is solved - 
![CIMG5317](https://user-images.githubusercontent.com/42438222/131329247-3a56508f-a958-4356-ac32-d8fa0e5e54ed.JPG)
Should I open the usb keyboard issue seperately?

**Comment by chregu82** [comment]
I don't have a working MBR at the moment, that I could show you. Glad it's working now. Please open a new issue.

**Comment by willtco** [comment]
Thanks for your help.
