### ISSUE TITLE
Composite output

### ISSUE THREAD

**Issue by esalgado** [fbergama/pigfx#69]
Hello!

is it possible to use the Composite output instead of the HDMI? I.E. to hook it up to an old TV

Thanks for this awesome project :)

**Comment by chregu82** [comment]
Hi
As far as I know this should work out of the box.

**Comment by esalgado** [comment]
Hi! Thanks for the reply, I have tried with a working Composite cable, tested with Raspbian. Does not work with PiGFX on Pi 4:

https://www.raspberrypi.com/documentation/computers/config_txt.html

> On the Raspberry Pi 4, composite output is disabled by default, due to the way the internal clocks are interrelated and allocated. Because composite video requires a very specific clock, setting that clock to the required speed on the Pi 4 means that other clocks connected to it are detrimentally affected, which slightly slows down the entire system. Since composite video is a less commonly used function, we decided to disable it by default to prevent this system slowdown.

> To enable composite output, use the enable_tvout=1 option. As described above, this will detrimentally affect performance to a small degree.

Thanks!

**Comment by chregu82** [comment]
Have you tried putting a config.txt onto the SD card with enable_tvout=1 ?

**Comment by esalgado** [comment]
OMG... yes it works!! I did not know I could also use config.txt with this...

Thanks a lot for your support :)
