### ISSUE TITLE
New Line/Enter not working in certian situations. 

### ISSUE THREAD

**Issue by smarinel** [fbergama/pigfx#71]
I have the newest build running on a Pi Zero W/RC2014 using CP/M

I can generally type fine at the CP/M prompt but inside ZDE16 or Zork1 I cannot hit enter to submit a command or go to a new line. I tried messing with the LF/CR options in the config file but nothing was working. Any idea what could be going on here?

**Comment by chregu82** [comment]
Every single time I heard about such an issue, it was LF instead of CR or CR instead of LF. Are you sure that your config file is read during boot? Please check your PiGFX boot screen.

**Comment by smarinel** [comment]
I see an error about the Master Boot Record but no mention of the config file - I suppose it can't actually load the file system? It reads it as a valid SD Card 3. Does this mean I need to maybe try a new format or physical card?

**Comment by chregu82** [comment]
It seems that this is the problem. It fails reading the filesystem and because of that it can't read the config file. You should make sure that there is only one partition on the card or try using a different card.

**Comment by smarinel** [comment]
Thanks for the help. Switching to an older card with lower capacity seems to have worked. 

For future folks looking at this - you need to have the config be read and change LF endings to be CR (not LFCR) to get PiGFX working well on an RC2014, at least at the time of writing.

**Comment by paulwratt** [comment]
@chregu82 

What was the sd-card size that failed, and the one that worked?

Also what was the filesystem that failed and worked (it might be related to the size)?
