### ISSUE TITLE
Hotswap USB keyboard...is this possible?

### ISSUE THREAD

**Issue by ProgrammingCube** [fbergama/pigfx#74]
I use my pigfx card with a usb switch, so I can use my nice mechanical keyboard for both my desktop and my cp/m machine at the press of a button. However, when I switch away from the card and back, I have to reset the pi before the keyboard can work again.

Is this possible to fix in the code as it is?

**Comment by chregu82** [comment]
PiGfx uses USPI for connecting USB devices. Unfortunately it does not support dynamic attachments. It would need huge efforts do do this.

**Comment by ProgrammingCube** [comment]
Ahh, I see
