### ISSUE TITLE
Feature request: Configurable terminal speed

### ISSUE THREAD

**Issue by linker3000** [fbergama/pigfx#9]
The ability to choose terminal speeds - at least 115200 and 57600 - would be useful.

**Comment by piecafe** [comment]
@linker3000 In case it helps, you might like to know that you can tweak/hack the terminal speed by adding/modifying the `config.txt` file on the SD card. The default value for `init_uart_clock` is `3000000` and I found that by dividing this by 3 I can run at 38400 baud to match my down-clocked RC2014 bus. Not the most elegant solution, but seems to work as a workaround.

**Comment by chregu82** [comment]
Terminal speed is now configurable in the config.txt file.
